---
output: 
 bookdown::markdown_document2:
    base_format: "officedown::rdocx_document"
    number_sections: yes
    toc: yes
    tables:
      style: Table
      layout: autofit
      width: 1.0
      caption:
        style: Table Caption
        pre: 'Table '
        sep: ': '
      conditional:
        first_row: true
        first_column: false
        last_row: false
        last_column: false
        no_hband: false
        no_vband: true
    pandoc_args: 
      - "--metadata-file=Header/header_common.yaml"
      - '--lua-filter=Filters/scholarly-metadata.lua'
      - '--lua-filter=Filters/author-info-blocks.lua'
      - '--lua-filter=Filters/pagebreaks.lua'
params:
  existing_predrs_ls: !r NULL
  output_type_1L_chr: Word
  subtitle_1L_chr: "Catalogue of longitudinal models"
  root_dir_1L_chr: ./
  section_type_1L_chr: "#"
  X: NULL
subtitle: "`r params$subtitle_1L_chr`"
date: "`r format.Date(Sys.Date(),'%B %d, %Y')`"
graphics: yes
---

```{r setup, include=FALSE}
library(specific)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(comment = NA)
knitr::opts_knit$set(root.dir = params$root_dir_1L_chr)
```

```{r, child=c('../Child_RMDs/_make_ctlg.Rmd')}
```